### PR TITLE
Added models and modern error handling

### PR DESCRIPTION
**Pull request by DevanshB10**

### CODE REVIEW

**Comment by SatinderpalSingh** [comment]
send PR in projects branch

**Comment by DevanshB10** [comment]
> send PR in projects branch

Sir, projects branch isn't there in the forked repo, only main branch and gh-pages is there.

**Comment by SatinderpalSingh** [comment]
Pull the latest changes to your local branch from the main branch

**Comment by DevanshB10** [comment]
> Pull the latest changes to your local branch from the main branch

Sir, Git pull command shows it's up to date.

**Comment by SatinderpalSingh** [comment]
https://stackabuse.com/git-fetch-a-remote-branch/

**Pull request closed without merging**
